"""bookshelf table

Revision ID: 606d6803aa0d
Revises: 
Create Date: 2021-01-17 00:19:29.052945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606d6803aa0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('birth', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_birth'), 'authors', ['birth'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_index(op.f('ix_authors_surname'), 'authors', ['surname'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=15), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.create_index(op.f('ix_books_pages'), 'books', ['pages'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('bookshelf',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_pages'), table_name='books')
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_surname'), table_name='authors')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_birth'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
