"""bookshelf table add stock column

Revision ID: 6249acbfba27
Revises: 606d6803aa0d
Create Date: 2021-01-17 00:22:30.301976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6249acbfba27'
down_revision = '606d6803aa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelf', sa.Column('stock', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookshelf', 'books', ['stock'], ['stock'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookshelf', type_='foreignkey')
    op.drop_column('bookshelf', 'stock')
    # ### end Alembic commands ###
